export const ROUTES = {
  HOME: '/',
  COURSES: '/courses',
  COURSE_DETAIL: '/courses/:id',
  COURSE_LEARN: '/courses/:id/learn',
  CART: '/cart',
  CHECKOUT: '/checkout',
  CHECKOUT_SUCCESS: '/checkout/success',
  MY_ORDERS: '/my-orders',
  MY_COURSES: '/my-courses',
  PROFILE: '/profile',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  ADMIN_COURSES: '/admin/courses',
  ADMIN_COURSE_NEW: '/admin/courses/new',
  ADMIN_COURSE_EDIT: '/admin/courses/:id/edit',
  ADMIN_COURSE_DETAIL: '/admin/courses/:id',
  ADMIN_TRANSACTIONS: '/admin/transactions'
} as const
